# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.define "myubuntu" do |myubuntu|
    myubuntu.vm.synced_folder"/home/ragnarokkrr/prj/rgn_vm_containers/vagrant_k8s/synced", "/vagrant"

    #myubuntu.vm.network "forwarded_port", guest: 80, host: 8080
    #myubuntu.vm.network "private_network", ip: "192.168.33.10"
    myubuntu.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

end
