VAGRANT_API = "2"

Vagrant.configure(VAGRANT_API) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network	"forwarded_port",	guest:	80,	host:	8080     # http
	config.vm.network	"forwarded_port",	guest:	443,	host:	8443   # https
  config.vm.network	"forwarded_port",	guest:	5984,	host:	55984  # couchdb


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.sudo = true
  end
end
