# -*- mode: ruby -*-
# vi: set ft=ruby :
#


Vagrant.configure(2) do |config|
  config.vm.box = "nrel/CentOS-6.5-x86_64"

  config.vm.define "zabbix" do |zabbix|

    zabbix.vm.network "forwarded_port", guest: 80, host: 8080
    zabbix.vm.network "private_network", ip: "192.168.33.10"

    zabbix.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "256"
    end
  end

  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "provisioning/entry-playbook.yml"

  #  ansible.sudo = true
    #ansible.raw_arguments = ["--connection=paramiko"]
    #ansible.inventory_path = "provisioning/inventory"
  #  ansible.raw_arguments = ["-vvvv"]
  #end



end
