VAGRANT_API = "2"

Vagrant.configure(VAGRANT_API) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define "proxy-active" do |proxy_active|
    proxy_active.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "proxy-bkp" do |proxy_bkp|
    proxy_bkp.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "hello-service1" do |hello_service1|
    hello_service1.vm.network "private_network", ip: "192.168.33.12"

  end

  config.vm.define "hello-service2" do |hello_service1|
    hello_service1.vm.network "private_network", ip: "192.168.33.13"

  end


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/microservices.yml"
    ansible.sudo = true
    ansible.raw_arguments = ["--connection=paramiko"]

    ansible.groups = {
      "spring-boot-microservices" => ["hello-service[1:2]"]
    }
  end



end
