# -*- mode: ruby -*-
# vi: set ft=ruby :
#

CEPH_HOSTS = [
  { name: 'ceph-node1', disk1: 'ceph-node1-osd1.vdi', disk2: 'ceph-node1-osd2.vdi', disk3: 'ceph-node1-osd3.vdi'},
  { name: 'ceph-node2', disk1: 'ceph-node2-osd1.vdi', disk2: 'ceph-node2-osd2.vdi', disk3: 'ceph-node2-osd3.vdi'},
  { name: 'ceph-node3', disk1: 'ceph-node3-osd1.vdi', disk2: 'ceph-node3-osd2.vdi', disk3: 'ceph-node3-osd3.vdi'}
]

CEPH_NODES = {
  ceph_nodes_list: ['ceph_node1','ceph_node2','ceph_node3'],
  ceph_prim_node: 'ceph_node1'
}

#{"ceph_nodes_list":["ceph_node1","ceph_node2","ceph_node3"], "ceph_prim_node": "ceph_node1"}


Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"


  config.vm.provider :virtualbox do |vb|
    vb.customize ["storagectl", :id, "--add", "sata", "--name", "SATA Controller",
      "--controller", "IntelAHCI", "--hostiocache", "on", "--portcount", 3]
  end

  CEPH_HOSTS.each_with_index do |ceph_host, i|
    config.vm.define ceph_host[:name] do |ceph_node|
      ceph_node.vm.hostname = ceph_host[:name]

      ceph_node.vm.network "private_network", ip: "192.168.57.1#{i}"
      #ceph_node.vm.synced_folder "/srv/data", "/data"

      ceph_node.vm.provider :virtualbox do |vb|
        vb.name = ceph_host[:name]

        vb.gui = false
        vb.memory = "512"
        vb.cpus = 1

        vb.customize ['createhd', '--filename', ceph_host[:disk1], '--size', 2 * 1024]
        vb.customize ['createhd', '--filename', ceph_host[:disk2], '--size', 2 * 1024]
        vb.customize ['createhd', '--filename', ceph_host[:disk3], '--size', 2 * 1024]

        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1,
            '--device', 0, '--type', 'hdd', '--medium', ceph_host[:disk1]]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 2,
            '--device', 0, '--type', 'hdd', '--medium', ceph_host[:disk2]]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 3,
            '--device', 0, '--type', 'hdd', '--medium', ceph_host[:disk3]]

      end
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/entry-playbook.yml"

    ansible.sudo = true
    ansible.raw_arguments = ["--connection=paramiko"]
    ansible.groups = {
      "ceph_nodes" => ["ceph-node[1:3]"],
      "ceph_primary_node" => ["ceph-node1"],
    }

    
    #ansible.extra_vars = {
    #  ceph_nodes_list: 'ceph_node1 ceph_node2 ceph_node3',
    #  ceph_primary_node: 'ceph_node1'
    #}

    #ansible.raw_arguments = ['-vvvv']
    #ansible.inventory_path = "provisioning/inventory"
  end



end
