# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|


  config.vm.box = "suse/sles11sp3"


  config.vm.define "java-mservice" do |cli|


    # config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.network "private_network", ip: "192.168.33.10"

    # config.vm.network "public_network"

    # config.vm.synced_folder "../data", "/vagrant_data"

    config.vm.provider "virtualbox" do |vb|
       # Display the VirtualBox GUI when booting the machine
       vb.gui = false

       # Customize the amount of memory on the VM:
       vb.memory = "256"
    end

  end


  config.vm.define "java_camel" do |java_camel|
    # config.vm.network "forwarded_port", guest: 80, host: 8080

    java_camel.vm.network "private_network", ip: "192.168.33.20"

    # config.vm.synced_folder "../data", "/vagrant_data"

    java_camel.vm.synced_folder ".", "/vagrant", disabled: true

    java_camel.vm.provider "virtualbox" do |vb|
       # Display the VirtualBox GUI when booting the machine
       vb.gui = false

       # Customize the amount of memory on the VM:
       vb.memory = "512"
    end

    java_camel.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/java_camel.yml"
      ansible.sudo = true
      ansible.raw_arguments = ["--connection=paramiko"]

      ansible.groups = {
        "devhosts" => ["java_camel"]
      }
    end

  end

  config.vm .define "linuxupdate" do |linuxupdate|
    file_server.vm.box = "ubuntu/trusty64"

    file_server.vm.provider "virtualbox" do |vb|
       # Display the VirtualBox GUI when booting the machine
       vb.gui = false

       # Customize the amount of memory on the VM:
       vb.memory = "256"
    end

  end


end
