# -*- mode: ruby -*-
# vi: set ft=ruby :
#

GLUSTER_HOSTS = [
  { name: 'gluster-node1', disk1: 'gluster-node1-osd1.vdi', disk2: 'gluster-node1-osd2.vdi', disk3: 'gluster-node1-osd3.vdi'},
  { name: 'gluster-node2', disk1: 'gluster-node2-osd1.vdi', disk2: 'gluster-node2-osd2.vdi', disk3: 'gluster-node2-osd3.vdi'} ,
   { name: 'gluster-node3', disk1: 'gluster-node3-osd1.vdi', disk2: 'gluster-node3-osd2.vdi', disk3: 'gluster-node3-osd3.vdi'} ,
    { name: 'gluster-node4', disk1: 'gluster-node4-osd1.vdi', disk2: 'gluster-node4-osd2.vdi', disk3: 'gluster-node4-osd3.vdi'}
]

$script_gluster_server = <<SCRIPT
  apt-get update && apt-get upgrade -y

  echo "storage"
  apt-get install xfsprogs -y
  mkfs.xfs -i size=512 /dev/sdb
  mkfs.xfs -i size=512 /dev/sdc
  mkdir -p /storage/glusterfs/vol0/brick1/
  mkdir -p /storage/glusterfs/vol0/brick2/
  echo '/dev/sdb /storage/glusterfs/vol0/brick1 xfs defaults 1 2' >> /etc/fstab
  echo '/dev/sdc /storage/glusterfs/vol0/brick2 xfs defaults 1 2' >> /etc/fstab
  mount -a


  echo "going to install gluster"
  apt-get install glusterfs-server -y
  service glusterfs-server status



SCRIPT

$script_gluster_client = <<SCRIPT
  apt-get update && apt-get upgrade -y
  apt-get install glusterfs-client -y

SCRIPT


Vagrant.configure(2) do |config|
  #config.vm.box = "centos/7"
  config.vm.box = "ubuntu/trusty64"

  #config.vm.provider :virtualbox do |vb|
  #  vb.customize ["storagectl", :id, "--add", "sata", "--name", "SATA Controller",
  #    "--controller", "IntelAHCI", "--hostiocache", "on", "--portcount", 2]
  #end
  #
  config.vm.define "gluster-client" do |gluster_client|
    gluster_client.vm.network "private_network", ip: "192.168.57.20"

    gluster_client.vm.hostname = "gluster-client"
    gluster_client.vm.provision "shell", inline: $script_gluster_client
    gluster_client.vm.provider :virtualbox do |vb|
      vb.name = "gluster-client"

      vb.gui = false
      vb.memory = "256"
      vb.cpus = 1
    end
  end

  GLUSTER_HOSTS.each_with_index do |gluster_host, i|
    config.vm.define gluster_host[:name] do |gluster_node|

      gluster_node.vm.hostname = gluster_host[:name]

      gluster_node.vm.network "private_network", ip: "192.168.57.1#{i}"

      gluster_node.vm.network :forwarded_port, guest: 22, host: 2301 + i, auto_correct: false # for external provisioning

      #gluster_node.vm.synced_folder "#{Dir.pwd}/data", "/home/vagrant/data", create: true

      # https://github.com/oscar-stack/vagrant-hosts
      # vagrant plugin install vagrant-hosts
      gluster_node.vm.provision :hosts, :sync_hosts => true

      gluster_node.vm.provider :virtualbox do |vb|
        vb.name = gluster_host[:name]

        vb.gui = false
        vb.memory = "256"
        vb.cpus = 1

        file_to_disk1 = gluster_host[:disk1]
        file_to_disk2 = gluster_host[:disk2]


        #https://github.com/mitchellh/vagrant/issues/4015
        unless File.exist?(File.expand_path("#{file_to_disk1}"))


          # /dev/sda
          vb.customize ['createhd', '--filename', file_to_disk1, '--format', 'VDI', '--size', 5 * 1024]
          # /dev/sdb
          vb.customize ['createhd', '--filename', file_to_disk2, '--format', 'VDI', '--size', 7 * 1024]
        end

        vb.customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', 1,
            '--device', 0, '--type', 'hdd', '--medium', file_to_disk1]

        vb.customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', 2,
            '--device', 0, '--type', 'hdd', '--medium', file_to_disk2]


        # change the network card hardware for better performance
        vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
        vb.customize ["modifyvm", :id, "--nictype2", "virtio" ]

        # suggested fix for slow network performance
        # see https://github.com/mitchellh/vagrant/issues/1807
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end

      gluster_node.vm.provision "shell", inline: $script_gluster_server
    end
  end

  ANSIBLE_GROUPS = {
    # "gluster_nodes" => ["gluster-node[1:3]"],
    "gluster_nodes" => ["gluster-node1", "gluster-node2", "gluster-node3", "gluster-node4"],
    "gluster_primary_node" => ["gluster-node1"],
  }

  # https://github.com/MatthewMi11er/vai
  # vagrant plugin install vai
  config.vm.provision :vai do |ansible|
    ansible.inventory_dir = 'inventory/'
    ansible.inventory_filename='gen_inv'

    ansible.groups = ANSIBLE_GROUPS

  end


  #config.vm.provision :ansible do |ansible|
  #  ansible.playbook = "provisioning/glusterfs-install.yml"
  #  ansible.sudo = true
  #  ansible.raw_arguments = ["--connection=paramiko"]

  #  ansible.groups = ANSIBLE_GROUPS

    #ansible.extra_vars = {
    #  gluster_nodes_list: 'gluster_node1 gluster_node2 gluster_node3',
    #  ceph_primary_node: 'gluster_node1'
    #}

    #ansible.raw_arguments = ['-vvvv']
#  end



end
