# -*- mode: ruby -*-
# vi: set ft=ruby :
#

$script = <<SCRIPT
    sudo apt-get update
    sudo apt-get -y install ansible

    cd /vagrant


SCRIPT


NODE_INSTANCES = 2

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  (1..NODE_INSTANCES).each do |i|
    config.vm.define "node-#{i}" do |nginx|

      nginx.vm.synced_folder './synced', '/vagrant' #, type: 'nfs'

      nginx.vm.network "forwarded_port", guest: 80, host: 8090 + i
      nginx.vm.network "private_network", ip: "192.168.33.2#{i}"

      nginx.vm.provision "shell", inline: $script


      nginx.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "256"
      end
    end
  end

end
