# -*- mode: ruby -*-
# vi: set ft=ruby :
#


Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "burrow" do |burrow|

    #nginx.vm.network "forwarded_port", guest: 80, host: 8080 + i
    burrow.vm.network "private_network", ip: "192.168.33.11"

    burrow.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/entry.yml"
    ansible.sudo = true
    #ansible.raw_arguments = ["--connection=paramiko"]

    ansible.groups = {
      "burrow" => ["burrow"]
    }
  end


end
